source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

# gem 'sqlite3'
gem 'pg' # use postgresql instead of sqlite (which is not supported by sphinx)
gem 'execjs' # added by stefan
gem 'therubyracer' # added by stefan
gem 'authlogic' # authentication added by jochn
gem 'cancan' # cancan authorization added by jochn
gem 'thinking-sphinx', '2.0.10' # sphinx search engine, added by stefan

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

group :test, :development do
  gem "rspec-rails", ">= 2.7.0" # rspec testing framework, added by stefan
  # make the whole teststuff work (added by stefan):
  gem "factory_girl_rails", ">= 1.3.0"
  gem "cucumber-rails", ">= 1.1.1"
  gem "capybara", ">= 1.1.1"
  gem "database_cleaner", ">= 0.6.7"
  gem "launchy", ">= 2.0.5"
  gem "devise", ">= 1.4.9"
  gem "minitest"
end