# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

shows = Show.create([{ name: 'South Park', description: 'South Park is an American animated television series created by Trey Parker and Matt Stone for the Comedy Central television network.', date: '1997-08-13'},
	{ name: 'Dexter', description: 'Dexter is an American television drama series, which debuted on Showtime on October 1, 2006.', date: '2006-10-01' }, 
 	{ name: 'How I Met Your Mother', description: 'How I Met Your Mother is an American sitcom that premiered on CBS on September 19, 2005, created by Craig Thomas and Carter Bays.', date: '2005-09-19' }, 
 	{ name: 'Alphas', description: 'Alphas is an American science fiction dramatic television series created by Zak Penn and Michael Karnow. The series follows a group of people with superhuman abilities, known as "Alphas", as they work to prevent crimes committed by other Alphas.', date: '2011-07-11'}, 
 	{ name: 'The Big Bang Theory', description: 'The Big Bang Theory is an American sitcom created by Chuck Lorre and Bill Prady, both of whom serve as executive producers on the show, along with Steven Molaro. All three also serve as head writers. It premiered on CBS on September 24, 2007.', date: '2007-09-24'},
 	{ name: 'Familiy Guy', description: 'Family Guy is an American animated comedy created by Seth MacFarlane for the Fox Broadcasting Company. Since its debut on January 31, 1999, the show has broadcast 176 episodes and began airing its tenth season on September 25, 2011. The series centers on the dysfunctional Griffin family, which consists of father Peter (MacFarlane), mother Lois (Alex Borstein), daughter Meg (Mila Kunis; Lacey Chabert, 1999), son Chris (Seth Green), baby Stewie (MacFarlane) and Brian (MacFarlane), the family pet. The show is set in the fictional town of Quahog, Rhode Island, and lampoons American culture, often in the form of cutaway gags, and tangential vignettes.', date: '1999-01-31'},
 	{ name: 'My Little Pony: Friendship Is Magic', description: 'My Little Pony: Friendship Is Magic is an animated television series that premiered on October 10, 2010, on the United States cable network The Hub. Hasbro Studios and DHX Media Vancouver (formerly known as Studio B Productions) produce the series, which is based on Hasbro, Inc\'s My Little Pony line of toys and animated works. As of September 2011, the show is in its second season in the United States, and is broadcasting internationally in dozens of countries in over ten languages.', date: '2010-06-10'}])

 seasons = Season.create([
 	{ name: 'Season 1', number: '1', show_id: '1', description: 'The first season of the American animated television series South Park initially ran for 13 episodes on the US network Comedy Central, from August 13, 1997 to February 25, 1998.', date: '1997-08-13'},
	{ name: 'Season 2', number: '2', show_id: '1', description: 'A nice season of Southpark, bla bla', date: '2011-08-13'},
	{ name: 'Season 1', number: '1', show_id: '2', description: 'The first season of Dexter is an adaptation of Jeff Lindsay\'s first novel in the Dexter series, Darkly Dreaming Dexter.', date: '2006-10-01'},
 	{ name: 'Season 2', number: '2', show_id: '2', description: 'A nice season of Dexter', date: '2007-09-30'},
 	{ name: 'Season 3', number: '3', show_id: '2', description: 'A nice season of Dexter, bla bla', date: '2008-09-28'},
 	{ name: 'Season 1', number: '1', show_id: '3', description: 'The first season of the American television comedy series How I Met Your Mother premiered on September 19, 2005 and concluded on May 15, 2006.', date: '2005-09-19'},
 	{ name: 'Season 2', number: '2', show_id: '3', description: 'A nice season of How I met your mother, bla bla', date: '2006-10-19'},
 	{ name: 'Season 3', number: '3', show_id: '3', description: 'A nice season of How I met your mother, bla bla', date: '2007-10-12'},
  	{ name: 'Season 1', number: '1', show_id: '4', description: 'The first season of Alphas aired on July 11, 2011', date: '2011-07-11'},
  	{ name: 'Season 5', number: '5', show_id: '5', description: 'This is a list of episodes for the fifth season of the American sitcom The Big Bang Theory, which began airing on CBS on September 22, 2011.', date:'2011-09-22'},
  	{ name: 'Season 1', number: '1', show_id: '5', description: 'The first season of the American sitcom The Big Bang Theory was originally aired on CBS from September 24, 2007 to May 19, 2008 over 17 episodes. An unaired pilot also exists.', date:'2007-09-24'},
  	{ name: 'Season 10', number: '10', show_id: '6', description: 'Family Guy\'s tenth season debuted on the Fox network, on September 25, 2011. The series follows the Griffin family, a dysfunctional family consisting of father Peter, mother Lois, daughter Meg, son Chris, baby Stewie and Brian, the family pet, who reside in their hometown of Quahog. The executive producers for the tenth production season are Seth MacFarlane, Chris Sheridan, Danny Smith, Mark Hentemann, Steve Callaghan, Alec Sulkin, and Wellesley Wild. The showrunners are Hentemann and Callaghan.', date: '2011-09-25'},
  	{ name: 'Season 2', number: '2', show_id: '7', description: 'The second season premiered on September 17th, 2011, as one of the returning series on The Hub for 2011-2012 schedule.', date:'2011-09-17'}
  	])

 episodes = Episode.create([
 	{ name: 'Cartman Gets an Anal Probe', number: '1', season_id: '1', description: 'Cartman Gets an Anal Probe is the first episode of the animated television series South Park. It first aired on Comedy Central', date: '1997-08-13'},
 	{ name: 'Weight Gain 4000', number: '2', season_id: '1', description: 'Weight Gain 4000 is the second episode of the first season of the animated television series South Park. It first aired on Comedy Central in the United States on August 20, 1997.', date: '1997-08-20'},
 	{ name: 'Volcano', number: '3', season_id: '1', description: '"Volcano" is the third episode of the animated television series South Park. It originally aired on Comedy Central in the United States on August 27, 1997. In the episode, the four main characters, Stan, Kyle, Cartman and Kenny, go on a hunting trip with Stan\'s uncle Jimbo and his war buddy Ned.', date: '1997-08-27'},
 	{ name: 'Big Gay Al\'s Big Gay Boat Ride', number: '4', season_id: '1', description: 'Big Gay Al\'s Big Gay Boat Ride is the fourth episode of the first season of the animated television series South Park. It originally aired on September 3, 1997 on Comedy Central in the United States. The episode was written by series co-founders Trey Parker and Matt Stone, and directed by Parker.', date: '1997-09-03'},
 	{ name: 'Fancy New Episode', number: '1', season_id: '2', description: 'A nice episode of Southpark, blubb...', date: '2017-09-03'},
 	{ name: 'Some Episode', number: '2', season_id: '2', description: 'A nice episode of Southpark, blubb...', date: '2012-09-03'},
	{ name: 'Some Episode', number: '3', season_id: '2', description: 'A nice episode of Southpark, blubb...', date: '2012-09-12'},
	{ name: 'Dexter Episode', number: '1', season_id: '3', description: 'A nice episode of Dexter, blubb...', date: '2011-12-03'},
	{ name: 'Dexter Episode', number: '2', season_id: '3', description: 'A nice episode of Dexter, blubb...', date: '2011-12-09'},
	{ name: 'Dexter Episode', number: '3', season_id: '3', description: 'A nice episode of Dexter, blubb...', date: '2011-12-14'},
	{ name: 'The Recombination Hypothesis', number: '13', season_id: '10', description:'Upon arriving home, Sheldon discovers that the cutout of Mr. Spock he ordered is of Zachary Quinto, not Leonard Nimoy. As he gripes about this, Leonard notices Penny across the hall, and spontaneously asks her out on a date. Their dinner starts well, but soon goes sour when Leonard insists on over-analyzing their relationship. He comes home in a bad mood, causing Howard and Raj to assume he and Penny are on the outs. However, that night, Penny invites him over via text, and, after warning him not to talk, they have sex. They agree to keep their relationship secret. When everyone has dinner at the Cheesecake Factory, Leonard overplays his fake annoyance, genuinely angering Penny. They have a late-night argument, followed by more sex. Leonard tells Penny that he cannot imagine this ending well.
The scene shifts back to the hallway, with Sheldon still grousing about Mr. Spock--the whole episode was in Leonard\'s imagination. Nonetheless, he marches into Penny\'s apartment and asks her out. She asks if he\'s thought this over, and he replies that he has, but that they should go anyway. She agrees. The episode ends with Penny imagining herself very pregnant and marrying Leonard, reminding her to stop by the drugstore before the date.
Note: Leonard broke up with Priya prior to "The Good Guy Fluctuation," the seventh episode of the season.
Title reference: Leonard contemplating the ramifications of asking Penny out on a date.', date: '2012-01-19'}, 
	{ name: 'The Beta Test Initiation', number: '14', season_id: '10', description:'Leonard and Penny have started dating again. Anxious to avoid the mistakes of last time, Leonard suggests they have a Alpha test relationship: rather than getting angry with each other, they\'ll simply report any \'bugs\' they discover and fix them. This goes poorly. Leonard gives Penny an insultingly long list of her faults. When he tries to patch things up by taking her target shooting, he accidentally shoots himself in the toe.
Meanwhile, Raj develops a crush on his phone\'s virtual assistant, Siri and Sheldon and Amy start a podcast about the study of flags.
Recurring characters: John Ross Bowie as Barry Kripke Notable guest stars: Becky O\'Donohue as Siri
Title reference: Leonard inventing a system in which Penny and he can communicate their annoyances in the relationship to improve upon it. Penny incorrectly dubs the technique a "beta test" instead of an "alpha test," and Leonard corrects her.', date: '2012-01-26'},
	{ name: 'The Friendship Contraction', number: '15', season_id: '10', description:'Sheldon\'s selfish demands force Leonard to reconsider their friendship. Meanwhile, Howard tries to pick his astronaut nickname.
Recurring characters: Kevin Sussman as Stuart Bloom
Notable guest stars: Mike Massimino as himself', date: '2012-02-02'},
	{ name: 'Livin\' on a Prayer', number: '12', season_id: '12', description: 'When Stewie\'s new best friend falls ill, Lois takes him to the hospital where she finds out he has a critical, but treatable, disease. However, the boy\'s parents refuse treatment due to their religious beliefs, leaving Lois no choice but to take drastic measures to seek treatment for the boy herself. Meanwhile, Peter has a religious experience of his own.', date: '2012-01-29'},
	{ name: 'Tom Tucker: The Man and His Dream', number: '13', season_id: '12', description: 'When Peter decides to become a famous actor, he becomes Tom Tucker\'s agent as his first step toward stardom. Meanwhile, Chris dates a girl who looks disturbingly like a member of the Griffin household.', date: '2012-02-12'},
	{ name: 'The Super Speedy Cider Squeezy 6000', number: '15', season_id: '13', description: 'Cider Season has come once again and the Apple family is ready to make their famous cider. But this year, two twin colts known as the Flim Flam Brothers arrive to show off their new invention, the super speedy cider squeezy 6000 promising to make more cider in half the time. When they refuse to share business with the twins, the Apple family is instead challenged to a contest. Can Applejack, Granny Smith, Apple Bloom and Big Macintosh pull through and defeat the machine, especially with Sweet Apple Acres on the line? ', date: '2012-01-28'},
	{ name: 'Read it and Weep', number: '16', season_id: '13', description: 'Rainbow Dash discovers the joys of reading when staying in a hospital.', date: '2012-02-04'}
 ])

 users = User.create(:name => "admin", :password => "admin", :password_confirmation => "admin", :email => "admin@abc.com", :role => "admin")